export * from "./HomePage/HomePage";
export * from "./Cryptocurrencies/Cryptocurrencies";
export * from "./Cryptodetails/CryptoDetails";
export * from "./Exchanges/Exchanges";
export * from "./News/News";
export * from "./Login/Login";
export * from "./Register/Register";
export * from "./Recovery/Recovery";
export * from "./Profile/Profile";